# Generated by Django 5.0.6 on 2024-06-29 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='cliente',
            field=models.CharField(max_length=100),
        ),
    ]
