# Generated by Django 5.0.6 on 2024-07-01 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_activity_description_activity_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='photo',
            field=models.CharField(default='', max_length=500),
        ),
    ]
